# Setup
title:               '동규의 깃블로그'
tagline:             '깃은 깃발이란 뜻이 아니라 깃허브의 그 깃임'
description:         '유레카 프로젝트 수업 중 제작한 깃 블로그 입니다.  Made by <a href="https://www.instagram.com/movinggyu_/" target="_blank">@movinggyu_</a>.'
url:                 http://movinggyu.github.io
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              movinggyu
  url:               https://www.instagram.com/movinggyu_
  email:             dlehdrb0822@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
